const ADD_ARTICLE = "ADD_ARTICLE";
const DELETE_ARTICLE = "DELETE_ARTICLE";
const DATA_REQUESTED = 'DATA_REQUESTED';
const DATA_LOADED = 'DATA_LOADED';
const API_ERRORED = 'API_ERRORED';

export {
    ADD_ARTICLE,
    DELETE_ARTICLE,
    DATA_REQUESTED,
    DATA_LOADED,
    API_ERRORED
}